#!/usr/bin/env python

"""
//===---------------------------------------------------------------------===//
//
// This source file is part of the SWAN open source project
//
// Copyright (c) 2019 Maple @ University of Alberta
// All rights reserved. This program and the accompanying materials (unless
// otherwise specified by a license inside of the accompanying material)
// are made available under the terms of the Eclipse Public License v2.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v20.html
//
//===---------------------------------------------------------------------===//
"""

import argparse
import os
import os.path
from os import path
import subprocess
import sys
from constants import *

def same_tag(tag, branch=False):
    cmd = "git rev-parse --abbrev-ref HEAD" if branch else "git describe --abbrev=0"
    print(cmd)
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
    cur = proc.stdout.read().strip(' \t\n\r')
    if tag != cur:
        print("New tag detected. New: " + tag + ", Current: " + cur)
    return tag == cur

def update_swift(tag):
    if not path.exists(SWIFT_DIR):
        chdir(PACKAGES_DIR)
        system("git clone --branch " + tag + " " + SWIFT_REPO_URL)
        # First clone without tag since tag may not exist for each subrepo.
        system("/." + SWIFT_UTILS_DIR + "update-checkout --clone")
        system("/." + SWIFT_UTILS_DIR + "update-checkout --tag " + tag)
        chdir(ROOT)
        return
    chdir(SWIFT_DIR)
    if not same_tag(tag):
        system("git reset --hard HEAD")
        system("git fetch")
        system("git checkout -f " + tag)
        system("/." + SWIFT_UTILS_DIR + "update-checkout --tag " + tag)
    chdir(ROOT)

def update_wala(tag):
    if not path.exists(WALA_DIR):
        chdir(PACKAGES_DIR)
        system("git clone --branch " + tag + " " + WALA_REPO_URL)
        chdir(ROOT)
        return
    chdir(WALA_DIR)
    if not same_tag(tag):
        system("git fetch")
        system("git checkout -f " + tag)
    chdir(ROOT)

def update_swan_vscode(tag):
    if not path.exists(VSCODE_DIR):
        chdir(PACKAGES_DIR)
        system("git clone " + SWAN_VSCODE_REPO_URL + " --branch " + tag)
        chdir(SWAN_VSCODE_DIR)
        system("npm install")
        chdir(ROOT)
        return
    chdir(SWAN_VSCODE_DIR)
    if not same_tag(tag, True):
        system("git fetch")
        system("git checkout " + tag)
        system("git pull")
        system("npm install")
    else: # Since we actively update the extension
        system("git fetch")
        system("git pull")
        system("npm install")
    chdir(ROOT)

def get_tags():
    tags = {}
    with open(TAGS_FILE, 'r') as file:
        for line in file:
            if '=' in line:
                key, value = line.split('=', 1)
                tags[key.strip()] = value.strip()
    return tags["SWIFT_TAG"], tags["WALA_TAG"], tags["VSCODE_BRANCH"]

def main():
    check_dir()

    parser = argparse.ArgumentParser()
    parser.add_argument("--clean", help="Deletes packages/ and re-clones.", action="store_true")
    args = parser.parse_args()

    if args.clean:
        system("rm -rf " + PACKAGES_DIR)

    if not path.exists(PACKAGES_DIR):
        system("mkdir " + PACKAGES_DIR)

    swift_tag, wala_tag, vscode_tag = get_tags()

    update_swift(swift_tag)
    update_wala(wala_tag)
    update_swan_vscode(vscode_tag)

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(1)
