#!/usr/bin/env python

"""
//===---------------------------------------------------------------------===//
//
// This source file is part of the SWAN open source project
//
// Copyright (c) 2019 Maple @ University of Alberta
// All rights reserved. This program and the accompanying materials (unless
// otherwise specified by a license inside of the accompanying material)
// are made available under the terms of the Eclipse Public License v2.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v20.html
//
//===---------------------------------------------------------------------===//
"""

import argparse
import os
import sys
import subprocess
from subprocess import Popen, PIPE, STDOUT

def main():

    parser = argparse.ArgumentParser()
    parser.add_argument("-project-path", required=True)
    parser.add_argument("-xcode-options", required=True)
    parser.add_argument("-xconfig-path", required=True)
    args = parser.parse_args()

    cmd = "xcodebuild -project " + args.project_path + \
    " -xcconfig " + args.xconfig_path + " " + args.xcode_options
    print(cmd)
    os.system(cmd)

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(1)
